### ISSUE TITLE
ModuleNotFoundError: No module named 'wx'

### ISSUE THREAD

**Issue by wilcoln** [RMPR/atbswp#1]
```
git clone https://github.com/rmpr/atbswp.git && cd atbswp
sudo apt install python3-wxgtk4.0
python3 atbswp.py
```

> Cloning into 'atbswp'...
> remote: Enumerating objects: 13, done.
> remote: Counting objects: 100% (13/13), done.
> remote: Compressing objects: 100% (13/13), done.
> remote: Total 13 (delta 0), reused 13 (delta 0), pack-reused 0
> Unpacking objects: 100% (13/13), done.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-wxgtk4.0 is already the newest version (4.0.1+dfsg-2).
> The following packages were automatically installed and are no longer required:
>   python-wxgtk3.0 python-wxversion
> Use 'sudo apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

```
Traceback (most recent call last):
  File "atbswp.py", line 19, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
```

**Comment by RMPR** [comment]
What's the output of `python3 -m pip list`?

**Comment by RMPR** [comment]
After a quick read, I wasn't able to find any package inside the debian repository, so you will have to install manually from the wheel file [here](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-9/)
