### ISSUE TITLE
How to stop infinite playback?

### ISSUE THREAD

**Issue by sojusnik** [RMPR/atbswp#10]
The only thing that helps is to force quit the app.

Happens on Ubuntu 19.10.

BTW, love your app, many thanks!

**Comment by RMPR** [comment]
Thank you very much, actually the infinite playback can only be stopped as you guessed, nevetheless, it's on the roadmap, will let you know when it's implemented.

**Comment by WesleyMPG** [comment]
Hi, I solved this problem. How can i contribute?
Here is a video showing it solved:

[https://youtu.be/II976NEK4YY](url)

**Comment by RMPR** [comment]
That's great! Feel free to open a PR[0] so we can discuss it further.


0: https://github.com/RMPR/atbswp/pulls
