### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by sojusnik** [RMPR/atbswp#11]
Assigned them to different F2-F12 keys, but nothing happens after pressing those, even if the main window of your app is active.

BTW, would be great, if it would be possible to assign keyboard shortcuts other than F2-F12.

Happens on Ubuntu 19.10.

**Comment by RMPR** [comment]
> Assigned them to different F2-F12 keys, but nothing happens after pressing those, even if the main window of your app is active.

Keyboard shortcuts is a work in progress, only the playback hotkey works now

> BTW, would be great, if it would be possible to assign keyboard shortcuts other than F2-F12.

What for example? You need to understand that those keys were chosen because we didn't want them to interfere with the user recording a capture.

**Comment by sojusnik** [comment]
> Keyboard shortcuts is a work in progress, only the playback hotkey works now

Got ya!

> What for example? You need to understand that those keys were chosen because we didn't want them to interfere with the user recording a capture.

My bad, didn't consider that :)
