### ISSUE TITLE
Hotkey not working on Linux Mint 19

### ISSUE THREAD

**Issue by ghost** [RMPR/atbswp#28]
Hi there,
using the latest version of atbswp, manual recording and playback works well.
The issue is that the hotkeys doesn't work at all.
my system is Linux Mint 19 based on Ubuntu 18.04

This software is amazing, solving this issue would make thing better.
waiting for your reply

**Comment by RMPR** [comment]
What DE are you using?

**Comment by deepseek** [comment]
cinnamon

**Comment by deepseek** [comment]
@RMPR

**Comment by RMPR** [comment]
Sounds like a bug with wxPython, will investigate more when I have time

**Comment by deepseek** [comment]
i installed wxPython using conda

**Comment by deepseek** [comment]
any progress

**Comment by RMPR** [comment]
This problem is not only on Linux Mint, but also on every *NIX I tested
atbswp on, I might take some time for me to understand what's going on.

**Comment by deepseek** [comment]
Which linux os and de does atbswp works perfectly on?

**Comment by geeknik** [comment]
I found that the hotkey works on Fedora 31, but only if `atbswp` has focus. As soon as another app gains focus, the hotkey quits working.

**Comment by RMPR** [comment]
A little update on this, a commit #31 just landed on developed attempting to
fix this, if you're interested in testing, these changes will probably
be in the next release anyway.

**Comment by RMPR** [comment]
Solved with
https://github.com/RMPR/atbswp/commit/8a127fa02e65db84b467f51cc6832621f664fc25
