### ISSUE TITLE
make a schedule feature for the script please

### ISSUE THREAD

**Issue by zultany** [RMPR/atbswp#40]
## Checklist

- [x] I use the latest release of atbswp
- [ ] The issue is not existing yet

## Verbose log

```
PASTE VERBOSE LOG HERE
```

### Operating System
linux

### Desktop Environment/Window Manager
linux

### Python version
3.8.6

## Description

the app needs schedule feature so anyone can schedule any sequence anytime he wants or difrente times without the need to go in to crontab and linux commands 
i have tried to make the python file work in crontab and i keep getting errors

**Comment by RMPR** [comment]
While I understand where you're coming from, I also think this is beyond the scope of atbswp. If you have issues managing cron jobs from the CLI, you can use a GUI frontend like [zeit](https://github.com/loimu/zeit)

**Comment by zultany** [comment]
What do you mean by you understand where I'm coming from ?
And that what i want is beyond the scope of atbswp ?
I found that the issue is because of the library pygui

The fix is : to make in crontab -e   display = 0

**Comment by RMPR** [comment]
On Sun Jan 10, 2021 at 8:36 AM WAT, zultany wrote:
> What do you mean by you understand where I'm coming from ?
> And that what i want is beyond the scope of atbswp ?
> I found that the issue is because of the library pygui
>
> The fix is : to make in crontab -e display = 0

It seems that I got what you were saying completely wrong, I'm sorry. If
your problem is solved I'll now close this issue.

**Comment by zultany** [comment]
i solved the problem but not the right way as stoping display option in
crontab have other disadvantages but really your software is awesome and
very smart keep on going there is alot of options you can add
the schedule feature as i told you and also a vision based clicking at it
is already in the pyautogui library
keep going mate

**Comment by RMPR** [comment]
You can join the [telegram community](https://t.me/atbswp) I sometimes post poll there about features to implement.
