### ISSUE TITLE
Threat or app was removed from this device.

### ISSUE THREAD

**Issue by ac5222** [RMPR/atbswp#48]
## Checklist

- [x] I use the latest release of atbswp
- [ ] The issue is not existing yet

## Verbose log

```
PASTE VERBOSE LOG HERE
```

### Operating System
Windows

## Description

WRITE DESCRIPTION HERE
When I try to download, it says that the program contains: Trojan:Win32/Zpevdo.B and restricts the download.

**Comment by RMPR** [comment]
What do you try to download? v0.1[0] or v0.2[1]? If it's the latter, it
might be normal. Just add an exception in your antivirus and verify that
the sha256 matches the file you downloaded.

Thanks.

0: https://github.com/RMPR/atbswp/releases/tag/v0.1

1: https://github.com/RMPR/atbswp/releases/tag/v0.2
