### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by RMPR** [RMPR/atbswp#49]
Following this poll https://t.me/atbswp/36, (while against it) I decided to gather 
advices for a new name. Feel free to propose a new one.

**Comment by RMPR** [comment]
atbswp

**Comment by Esdras123** [comment]
AutoMate
AutoMacro
AutoTask
MacroTask
AutoStuff

**Comment by RMPR** [comment]
Please, post each name as a separate post, the winner will be determined
by the number of thumbs up.

**Comment by dbitouze** [comment]
ClickRecord

**Comment by Esdras123** [comment]
AutoMate

**Comment by Esdras123** [comment]
AutoMacro

**Comment by Esdras123** [comment]
AutoTask

**Comment by Esdras123** [comment]
MacroTask

**Comment by Esdras123** [comment]
AutoStuff

**Comment by baals** [comment]
QuickTask

**Comment by WesleyMPG** [comment]
SirMacro
