### ISSUE TITLE
Version 0.2 reports as version 0.1

### ISSUE THREAD

**Issue by bmn001** [RMPR/atbswp#52]
## Checklist
- [x] I use the latest release of atbswp
- [x] The issue is not existing yet

## Verbose log
n/a

### Operating System
Ubuntu 20.10

### Desktop Environment/Window Manager
X11 / Gnome 3.38.3

### Python version
3.8.6

## Description

The "About" section of the app reports it as being "v0.1" and has a copyright date of 2019, when in fact you're running **v0.2** which was released in **2021**.

**Comment by RMPR** [comment]
> The "About" section of the app reports it as being "v0.1" and has a
> copyright date of 2019, when in fact you're running **v0.2** which was
> released in **2011**.

You meant 2021? ;)
Thanks for reporting, I need to modify a couple of things, I'll have
this fixed for good very soon.

**Comment by RMPR** [comment]
Solved here
https://github.com/RMPR/atbswp/commit/f79d5824ba365920e5a3153c86b1fae8f1e74d16
