### ISSUE TITLE
Add to the AUR

### ISSUE THREAD

**Issue by ShawkMusic** [RMPR/atbswp#62]
## Checklist

- [x] I use the latest release of atbswp
- [x] The issue is not existing yet

## Verbose log

```
N/A
```

### Operating System
Linux 5.10.42-1-MANJARO

### Desktop Environment/Window Manager
KDE Plasma 5.21.5/KWin (X11)

### Python version
3.9.5

## Description

Is there any reason this isn't in the AUR? I would add it myself if I knew how. I tried following a tutorial but I've never done this before and I don't want to screw it up.

**Comment by RMPR** [comment]
The only reason it's not there is that I don't use Arch Linux and I
guess nobody really wanted it there. If you can try something that would
be great.

**Comment by ShawkMusic** [comment]
I'll give it a shot then.

**Comment by mauricedenassau** [comment]
This might be of some help https://itsfoss.com/create-pkgbuild/

**Comment by dginovker** [comment]
Created a package: https://aur.archlinux.org/packages/atbswp/

**Comment by ShawkMusic** [comment]
Thanks! I installed it
