### ISSUE TITLE
How to ignore mouse inputs?

### ISSUE THREAD

**Issue by ShawkMusic** [RMPR/atbswp#65]
## Checklist

- [x] I use the latest release of atbswp
- [x] The issue is not existing yet

## Verbose log

```
PASTE VERBOSE LOG HERE
```

### Operating System
Linux 5.10.42-1-MANJARO

### Desktop Environment/Window Manager
KDE Plasma, KWin (X11)

### Python version
3.9.5

## Description

How can I make it ignore mouse inputs and only record/play back keyboard inputs?
Whenever I press record and then switch windows, it includes the mouse movement made to do that and every time it loops it adds that unnecessary mouse motion which wastes time

**Comment by RMPR** [comment]
Right now it's not possible to do so, feel free to open a PR if you feel
like implementing this. A quick workaround is to remove all the mouse
actions in the generated temporary file. Namely moveTo, mouseDown and
mouseUp.
