### ISSUE TITLE
Increase playback speed

### ISSUE THREAD

**Issue by ShawkMusic** [RMPR/atbswp#66]
## Checklist

- [x] I use the latest release of atbswp
- [x] The issue is not existing yet

## Verbose log

```
PASTE VERBOSE LOG HERE
```

### Operating System
Linux 5.10.42-1-MANJARO

### Desktop Environment/Window Manager
KDE Plasma, KWin (X11)

### Python version
3.9.5

## Description

Is there any way I can make the playback faster?

**Comment by RMPR** [comment]
It's a WIP, will let you know when it's done.

**Comment by ShawkMusic** [comment]
> It's a WIP, will let you know when it's done.

Ok, thanks!

**Comment by RMPR** [comment]
I meant keep an eye on the develop branch and the releases :) Thanks for
reporting.

**Comment by 1-alex98** [comment]
I have linux ... same here

**Comment by RMPR** [comment]
This issue is superseded by #37
