### ISSUE TITLE
Hot key not recorded

### ISSUE THREAD

**Issue by borderline23** [RMPR/atbswp#69]
Hi
 windows 10
last versione of atbswp

the tool don't recognized hot key like ctrl + tab

**Comment by borderline23** [comment]
yautogui.moveTo(1058, 259)
pyautogui.moveTo(1037, 256)
pyautogui.moveTo(1016, 252)
pyautogui.mouseDown(1015, 254, 'left')
pyautogui.mouseUp(1015, 254, 'left')
time.sleep(12)
pyautogui.press('### This key is not supported yet')
pyautogui.press('### This key is not supported yet')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyUp('### This key is not supported yet')
time.sleep(1)

**Comment by RMPR** [comment]
This issue already exists #14
