### ISSUE TITLE
Add mouse speed recordin

### ISSUE THREAD

**Issue by borderline23** [RMPR/atbswp#70]
is possibile to add mouse speed on record?
will be great
thanks

**Comment by RMPR** [comment]
Hello, https://github.com/RMPR/atbswp/issues/37#issuecomment-726452929 here I talk a bit about that, I will expose this setting to the users at one point down the line

**Comment by RMPR** [comment]
Hello, I am happy to announce that a PR allowing you to do just that has been merged to master, if you feel adventurous, you can try before the next release, I am now closing this issue.
