### ISSUE TITLE
ModuleNotFoundError: No module named 'wx'

### ISSUE THREAD

**Issue by hemangjoshi37a** [RMPR/atbswp#79]
Traceback (most recent call last):
  File "atbswp/atbswp.py", line 21, in <module>
    import gui
  File "/home/hemang/atbswp/atbswp/gui.py", line 27, in <module>
    import control
  File "/home/hemang/atbswp/atbswp/control.py", line 36, in <module>
    from custom_widgets import SliderDialog
  File "/home/hemang/atbswp/atbswp/custom_widgets.py", line 20, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

[https://hjlabs.in/](https://hjlabs.in/)

**Comment by RMPR** [comment]
Hi, first of all, what OS are you using? Did you follow the install instructions in the README?

**Comment by zarraozaga** [comment]
Hi, I am facing the same error. Python 3.8, linux ubuntu 20.04

**Comment by RMPR** [comment]
> Hi, I am facing the same error. Python 3.8, linux ubuntu 20.04

Did you follow the install instructions in the README?

**Comment by CryptoXSS** [comment]
npm install wx

**Comment by CryptoXSS** [comment]
npm install wn

pip install wn

**Comment by hemangjoshi37a** [comment]
> > Hi, I am facing the same error. Python 3.8, linux ubuntu 20.04
> 
> Did you follow the install instructions in the README?

I followed all the readme instructions and i have all the latest versions of all the libraries also latest version of ubutnu.
