### ISSUE TITLE
Issue with CTRL+C and CTRL+V 

### ISSUE THREAD

**Issue by mmt999** [RMPR/atbswp#80]
This recorder is awesome, 

But it dont let you CTRL+C or CTRL+V copy and paste text, 

So it limit a lot the usability, as for a large amount of cases, this are important keys.

Let me know if you continue working on it or is obsolete, as there are issues from 2 years ago related to this point.

Thanks in advance,

**Comment by RMPR** [comment]
I guess you're talking about this issue? https://github.com/RMPR/atbswp/issues/14 
I am going to close this issue as it's a duplicate. Use the old issue to report.
