### ISSUE TITLE
run with docker ?

### ISSUE THREAD

**Issue by Sanix-Darker** [RMPR/atbswp#82]
## Checklist
N/A

## Verbose log
N/A

## Miscellaneous information
N/A

### Operating System
Any

### Desktop Environment/Window Manager
Any

## Description
Be able to start this with docker ?
If this is something that match the roadmap, i can take the ticket 😃

**Comment by RMPR** [comment]
Hey model, no problem with that as long as you make a PR, it will happily be merged. One word of caution though, I think it can be challenging (and wildly insecure) to capture and manipulate the input/output from the host using a docker container. A slightly better solution might be to package the app as a flatpak (or appimage), this is already tracked here https://github.com/RMPR/atbswp/issues/35. If you decide you want to take on this challenge instead.

**Comment by RMPR** [comment]
Any more comments on this?
