### ISSUE TITLE
Playback results are incorrect

### ISSUE THREAD

**Issue by bmn001** [RMPR/atbswp#88]
## Checklist

- [x] I use the latest release of atbswp
- [x] The issue is not existing yet

## Verbose log

```
#!/bin/env python3
# Created by atbswp v0.3.0 (https://git.sr.ht/~rmpr/atbswp)
# on 19 May 2022 
import pyautogui
import time
pyautogui.FAILSAFE = False

time.sleep(3)
pyautogui.keyDown('shift_left')
pyautogui.keyDown('T')
pyautogui.moveTo(651, 1042)
pyautogui.moveTo(646, 1068)
pyautogui.moveTo(638, 1100)
pyautogui.moveTo(631, 1133)
pyautogui.moveTo(621, 1170)
pyautogui.moveTo(607, 1212)
pyautogui.moveTo(593, 1254)
pyautogui.moveTo(587, 1276)
pyautogui.moveTo(583, 1298)
pyautogui.moveTo(579, 1322)
pyautogui.moveTo(577, 1344)
pyautogui.moveTo(577, 1366)
pyautogui.moveTo(577, 1400)
pyautogui.moveTo(577, 1426)
pyautogui.moveTo(577, 1452)
pyautogui.mouseDown(576, 1465, 'left')
pyautogui.mouseUp(576, 1465, 'left')
pyautogui.keyDown('shift_left')
pyautogui.keyDown('H')
pyautogui.keyUp('shift_left')
pyautogui.keyDown('e')
pyautogui.keyUp('h')
pyautogui.keyDown('l')
pyautogui.keyUp('e')
pyautogui.keyUp('l')
pyautogui.keyDown('l')
pyautogui.keyUp('l')
pyautogui.keyDown('o')
pyautogui.keyUp('o')
pyautogui.keyDown('.')
pyautogui.keyUp('.')
pyautogui.keyDown('space')
pyautogui.keyUp('space')
pyautogui.keyDown('space')
pyautogui.keyDown('shift_left')
pyautogui.keyUp('space')
pyautogui.keyDown('T')
pyautogui.keyUp('shift_left')
pyautogui.keyUp('t')
pyautogui.keyDown('h')
pyautogui.keyDown('i')
pyautogui.keyDown('s')
pyautogui.keyUp('h')
pyautogui.keyUp('i')
pyautogui.keyDown('space')
pyautogui.keyUp('s')
pyautogui.keyDown('i')
pyautogui.keyUp('space')
pyautogui.keyDown('s')
pyautogui.keyUp('i')
pyautogui.keyDown('space')
pyautogui.keyUp('s')
pyautogui.keyUp('space')
pyautogui.keyDown('a')
pyautogui.keyDown('space')
pyautogui.keyUp('a')
pyautogui.keyUp('space')
pyautogui.keyDown('t')
pyautogui.keyDown('e')
pyautogui.keyDown('s')
pyautogui.keyUp('t')
pyautogui.keyDown('t')
pyautogui.keyUp('s')
pyautogui.keyDown('.')
pyautogui.keyUp('e')
pyautogui.keyUp('t')
pyautogui.keyUp('.')
pyautogui.keyDown('enter')
pyautogui.keyUp('enter')
pyautogui.moveTo(604, 1445)
pyautogui.moveTo(613, 1417)
pyautogui.moveTo(614, 1395)
pyautogui.moveTo(626, 1369)
pyautogui.moveTo(647, 1345)
pyautogui.moveTo(668, 1326)
pyautogui.moveTo(690, 1306)
pyautogui.moveTo(707, 1285)
pyautogui.moveTo(715, 1257)
pyautogui.moveTo(717, 1234)
pyautogui.moveTo(715, 1206)
pyautogui.moveTo(715, 1180)
pyautogui.moveTo(715, 1154)
pyautogui.moveTo(716, 1131)
pyautogui.moveTo(720, 1108)
pyautogui.moveTo(729, 1083)
pyautogui.moveTo(738, 1060)
pyautogui.moveTo(707, 1037)
pyautogui.moveTo(673, 1022)
pyautogui.moveTo(646, 1011)
```

### Operating System
Ubuntu 22.04

### Desktop Environment/Window Manager
Gnome/X11

### Python version
3.10.4

## Description

So I can record macros just fine.  Mouse movements and keyboard presses _appear_ to be represented correctly in the log/script to my untrained eyes...  But playing back that script results in a lot of strange extra characters added and some are missing.

In the log above I record myself clicking a text editor window to give it focus (gedit, the default in gnome) and then typing:
```Hello.  This is a test.```
I then click atbswp to stop the recording.

I then play back that recording.  What shows up in the editor is this:
```ttttttttttHello.  his is a test.```
Sometimes it's
```tttttttttHello.  his is a test.```

I'm trying to record macros for a game where timing and accuracy are critical (Elden Ring) and I haven't been able to get any of my recordings to playback consistently.

I'm not smart enough to determine if this is a bug with atbswp or with pyautogui or with something else.

**Comment by RMPR** [comment]
Hey, thanks for reporting, unfortunately I am not able to reproduce the issue, with Ubuntu Budgie 20.04, and I don't think the issue is with atbswp per se.
My hunch is that Elden Ring takes up too much resources on your computer, and in turns that makes everything slower, including the recording (and replay maybe) of atbswp captures.

Elden Ring minimum requirements:

```
    Memory: 12 GB
    Graphics Card: NVIDIA GeForce GTX 1060 3GB or Radeon RX 580
    CPU: Intel Core i5-8400 or Ryzen 3 3300X
    File Size: 60 GB
    OS: Windows 10
```

Seem quite beefy, can you send the following information about your PC please?

- Amount of RAM
- Graphics card
- CPU

If any of those is below par, then it might explain why you have trouble capturing and replaying everything in a timely fashion.
